"""flask

Revision ID: 1fce9ae0bd2c
Revises: 
Create Date: 2026-03-25 13:25:14.359869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fce9ae0bd2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_order_payment', 'user', ['payment_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('feed')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_payment', type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
